language: node_js
node_js:
 - "node"
cache:
  directories:
    - node_modules
install:
- yarn install
script:
- npm run build
deploy:
  - provider: script
    script: now --token $NOW_TOKEN
    skip_cleanup: true