language: node_js
node_js:
 - "node"
cache:
  directories:
    - node_modules
install:
- yarn install
script:
- npm run build
before_deploy: yarn install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script
    script: now public --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
