language: node_js
node_js:
 - "node"
cache:
  directories:
    - node_modules
install:
- npm install --unsafe-perm
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: react-shopping-lists