language: node_js
node_js:
 - "node"
cache:
  directories:
    - node_modules
install:
- yarn install
script:
- npm run build
before_deploy: 
- yarn add now
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: react-shopping-lists