language: node_js
node_js:
 - "node"
cache:
  directories:
    - node_modules
install:
- yarn install
script:
- npm run build
before_deploy: 
- yarn add now
- now rm shopping-list --safe --yes --token $NOW_TOKEN 
deploy:
  - provider: script
    script:now --public --token $NOW_TOKEN  && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
