before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"
language: node_js
node_js:
 - "node"
cache:
  yarn: true
  directories:
    - node_modules
install:
- yarn install
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: react-shopping-lists